# Base Settings
## Site Setting
title: KAWOOU BOX
email: kawoou@kawoou.kr

username: "Kawoou"
description: "I got reprogrammed by a rogue AI<br />and now I'm totally cray"

baseurl: ""
# url: "http://yourdomain.com"

## Social Setting
#twitter_username: jekyllrb
facebook_username: kawoou
instagram_username: kawoou
github_username:  kawoou


# Dependency
gems:
  - jekyll-paginate
  - jekyll-redirect-from
  - jemoji


# Build settings
## Paginator
paginate: 5
paginate_path: "/page/:num/"

## Markdown
markdown: redcarpet

## Redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data", "tables"]

## Highlight
highlighter: pygments

permalink: pretty

#safe: true
lsi: true